# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
use_frameworks!
platform :ios, '10.0'
inhibit_all_warnings!
target 'ERModule' do
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'FMDB'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       end
    end
  end
  
end
